[package]
name = "rwal"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
clap-num = "1.0.2"
image = { version = "0.24.7", default-features = false, features = ["jpeg", "png"] }
imghdr = "0.7.0"
